# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'approval status',
                'verbose_name_plural': 'approval statuses',
            },
        ),
        migrations.CreateModel(
            name='Fetched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('delay', models.IntegerField()),
                ('response_code', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'fetched page',
                'verbose_name_plural': 'fetched pages',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('base_path', models.CharField(max_length=100)),
                ('enable_live_translation', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language')),
            ],
            options={
                'verbose_name': 'proxy site',
                'verbose_name_plural': 'proxy sites',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('allowed_domains', models.TextField()),
                ('start_urls', models.TextField()),
                ('deny', models.TextField()),
            ],
            options={
                'verbose_name': 'original website',
                'verbose_name_plural': 'original websites',
            },
        ),
        migrations.CreateModel(
            name='Translated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.ApprovalStatus')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language')),
            ],
            options={
                'verbose_name': 'translated page',
                'verbose_name_plural': 'translated page',
            },
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('last_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField()),
                ('last_checked_response_code', models.IntegerField()),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_referer', to='wip.Webpage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site')),
            ],
            options={
                'verbose_name': 'original page',
                'verbose_name_plural': 'original pages',
            },
        ),
        migrations.AddField(
            model_name='translated',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Webpage'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site'),
        ),
        migrations.AddField(
            model_name='fetched',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Webpage'),
        ),
    ]
