# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:08
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True),
        ),
    ]
