# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0002_auto_20151228_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
