# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0003_auto_20160105_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ('path',), 'verbose_name': 'original page', 'verbose_name_plural': 'original pages'},
        ),
        migrations.AddField(
            model_name='site',
            name='path_prefix',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
