# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0007_auto_20160202_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('xpath', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'page region',
                'verbose_name_plural': 'page regions',
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('text',),
                'verbose_name': 'source string',
                'verbose_name_plural': 'source strings',
            },
        ),
        migrations.CreateModel(
            name='StringInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=10, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'source string',
                'verbose_name_plural': 'source strings',
            },
        ),
        migrations.CreateModel(
            name='StringTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language')),
                ('string', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.String')),
                ('string_in_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.StringInPage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('text',),
                'verbose_name': 'string translation',
                'verbose_name_plural': 'string translations',
            },
        ),
        migrations.AlterModelOptions(
            name='pageversion',
            options={'ordering': ('webpage__site', 'webpage__path', '-time'), 'verbose_name': 'page version', 'verbose_name_plural': 'page versions'},
        ),
        migrations.AlterModelOptions(
            name='translatedversion',
            options={'verbose_name': 'translated version', 'verbose_name_plural': 'translated version'},
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='referer',
        ),
        migrations.AddField(
            model_name='translatedversion',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='translatedversion',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 2, 10, 8, 31, 433000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedversion',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 2, 10, 8, 51, 919000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='deny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='last_checked_response_code',
            field=models.IntegerField(verbose_name=b'Response code'),
        ),
        migrations.AddField(
            model_name='stringinpage',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site'),
        ),
        migrations.AddField(
            model_name='stringinpage',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.String'),
        ),
        migrations.AddField(
            model_name='stringinpage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Webpage'),
        ),
        migrations.AddField(
            model_name='pageregion',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site'),
        ),
    ]
