# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0008_auto_20160202_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(null=True)),
                ('checksum', models.CharField(max_length=32)),
                ('time', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site')),
            ],
            options={
                'ordering': ('-time',),
                'verbose_name': 'page block',
                'verbose_name_plural': 'page blocks',
            },
        ),
        migrations.CreateModel(
            name='StringInBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Block')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.String')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'string in block',
                'verbose_name_plural': 'strings in block',
            },
        ),
        migrations.CreateModel(
            name='TranslatedBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Block')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language')),
            ],
            options={
                'verbose_name': 'translated block',
                'verbose_name_plural': 'translated blocks',
            },
        ),
        migrations.AlterModelOptions(
            name='stringinpage',
            options={'ordering': ('-created',), 'verbose_name': 'string in page', 'verbose_name_plural': 'strings in page'},
        ),
    ]
