# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0009_auto_20160203_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Block')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Webpage')),
            ],
            options={
                'verbose_name': 'blok in page',
                'verbose_name_plural': 'bloks in page',
            },
        ),
    ]
