# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0010_blockinpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='xpath',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pageregion',
            name='xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stringinpage',
            name='xpath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
