# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0012_auto_20160204_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='no_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='no_translate',
            field=models.BooleanField(default=False),
        ),
    ]
