# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0013_auto_20160208_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language'),
        ),
    ]
