# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0014_block_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Txu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'txu source')),
                ('entry_id', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'id by provider')),
                ('reliability', models.IntegerField(default=1)),
                ('context_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Context id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('context_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Context type')),
            ],
            options={
                'ordering': ('-source__text',),
                'verbose_name': 'translation unit',
                'verbose_name_plural': 'translation units',
            },
        ),
        migrations.CreateModel(
            name='TxuSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='wip.Subject')),
                ('txu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txu', to='wip.Txu')),
            ],
            options={
                'verbose_name': 'txu subject',
                'verbose_name_plural': 'txu subjects',
            },
        ),
        migrations.RemoveField(
            model_name='stringinblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='stringinblock',
            name='site',
        ),
        migrations.RemoveField(
            model_name='stringinblock',
            name='string',
        ),
        migrations.RemoveField(
            model_name='stringinpage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='stringinpage',
            name='string',
        ),
        migrations.RemoveField(
            model_name='stringinpage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='stringtranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='stringtranslation',
            name='string',
        ),
        migrations.RemoveField(
            model_name='stringtranslation',
            name='string_in_page',
        ),
        migrations.RemoveField(
            model_name='stringtranslation',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='string',
            options={'ordering': ('text',), 'verbose_name': 'source or target string', 'verbose_name_plural': 'source or target strings'},
        ),
        migrations.AlterModelOptions(
            name='translatedversion',
            options={'verbose_name': 'translated version', 'verbose_name_plural': 'translated versions'},
        ),
        migrations.RemoveField(
            model_name='string',
            name='created',
        ),
        migrations.RemoveField(
            model_name='string',
            name='user',
        ),
        migrations.AlterField(
            model_name='block',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='webpages',
            field=models.ManyToManyField(blank=True, related_name='block', through='wip.BlockInPage', to='wip.Webpage', verbose_name=b'pages'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatedblock',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatedblock',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatedversion',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatedversion',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='page', through='wip.BlockInPage', to='wip.Block', verbose_name=b'blocks'),
        ),
        migrations.DeleteModel(
            name='StringInBlock',
        ),
        migrations.DeleteModel(
            name='StringInPage',
        ),
        migrations.DeleteModel(
            name='StringTranslation',
        ),
        migrations.AddField(
            model_name='txu',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_source', to='wip.String', verbose_name=b'source string'),
        ),
        migrations.AddField(
            model_name='txu',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='txu', through='wip.TxuSubject', to='wip.Subject', verbose_name=b'subjects'),
        ),
        migrations.AddField(
            model_name='txu',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_target', to='wip.String', verbose_name=b'target string'),
        ),
        migrations.AddField(
            model_name='txu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
