# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0015_auto_20160217_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='txu',
            options={'ordering': ('source__text', 'target__text'), 'verbose_name': 'translation unit', 'verbose_name_plural': 'translation units'},
        ),
        migrations.AlterField(
            model_name='string',
            name='text',
            field=models.TextField(),
        ),
    ]
