# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0016_auto_20160227_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageregion',
            name='site',
        ),
        migrations.AddField(
            model_name='txu',
            name='source_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='txu',
            name='target_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='PageRegion',
        ),
    ]
