# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0017_auto_20160228_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txu',
            name='context_id',
        ),
        migrations.RemoveField(
            model_name='txu',
            name='context_type',
        ),
        migrations.RemoveField(
            model_name='txu',
            name='source',
        ),
        migrations.RemoveField(
            model_name='txu',
            name='source_code',
        ),
        migrations.RemoveField(
            model_name='txu',
            name='target',
        ),
        migrations.RemoveField(
            model_name='txu',
            name='target_code',
        ),
        migrations.AddField(
            model_name='string',
            name='txu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Txu'),
        ),
        migrations.AlterField(
            model_name='blockinpage',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_in_page', to='wip.Block'),
        ),
        migrations.AlterField(
            model_name='translatedblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_block', to='wip.Block'),
        ),
    ]
