# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0018_auto_20160313_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txu',
            name='reliability',
        ),
        migrations.AddField(
            model_name='string',
            name='reliability',
            field=models.IntegerField(default=1),
        ),
    ]
