# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0020_auto_20160315_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='string',
            options={'ordering': ('-id',), 'verbose_name': 'string', 'verbose_name_plural': 'strings'},
        ),
        migrations.RemoveField(
            model_name='translatedversion',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='string',
            name='invariant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='string',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site'),
        ),
        migrations.AddField(
            model_name='translatedversion',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
