# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0021_auto_20160319_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockinpage',
            name='time',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blockinpage',
            name='xpath',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proxy',
            name='translate_deny',
            field=models.TextField(blank=True, help_text=b'Paths of pages not to processed online by the proxy', null=True, verbose_name=b'Deny translation'),
        ),
        migrations.AddField(
            model_name='site',
            name='extract_deny',
            field=models.TextField(blank=True, help_text=b'Paths of pages the string extractor should skip', null=True, verbose_name=b'Deny extractor'),
        ),
        migrations.AddField(
            model_name='site',
            name='translate_deny',
            field=models.TextField(blank=True, help_text=b'Paths of pages not to be submitted to offline translation', null=True, verbose_name=b'Deny translation'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='language',
            field=models.ForeignKey(blank=True, help_text=b'Possibly overrides the site language', null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='last_unfound',
            field=models.DateTimeField(help_text=b"Last time the page wasn't found", null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='xpath',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='deny',
            field=models.TextField(blank=True, help_text=b'Paths the spider should not follow', null=True, verbose_name=b'Deny spyder'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='last_checked',
            field=models.DateTimeField(help_text=b'Last time the page fetched with success', null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='no_translate',
            field=models.BooleanField(default=False, verbose_name=b'Do not translate'),
        ),
    ]
