# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0024_site_checksum_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='invariant_words',
            field=models.TextField(blank=True, help_text=b'Custom invariant words', null=True, verbose_name=b'Custom invariant words'),
        ),
        migrations.AddField(
            model_name='site',
            name='srx_rules',
            field=models.TextField(blank=True, help_text=b'Custom SRX rules extending the standard set', null=True, verbose_name=b'Custom SRX rules'),
        ),
    ]
