# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0025_auto_20160529_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='srx_initials',
            field=models.TextField(blank=True, help_text=b'Initials to be made explicit as SRX rules', null=True, verbose_name=b'Custom initials'),
        ),
    ]
