# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0027_auto_20160602_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='robots_txt',
            field=models.TextField(blank=True, help_text=b'The virtual content of the robots.txt page.', null=True, verbose_name=b'robots.txt'),
        ),
        migrations.AlterField(
            model_name='string',
            name='txu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='string', to='wip.Txu'),
        ),
    ]
