# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0028_auto_20160714_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
