# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0030_string_is_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='string_type',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'term'), (2, 'segment'), (3, 'fragment')], default=0, null=True, verbose_name=b'string type'),
        ),
        migrations.AddField(
            model_name='string',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='string',
            name='path',
            field=models.CharField(blank=True, default=b'/', max_length=200),
        ),
    ]
