# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0032_auto_20161030_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents', through='wip.BlockEdge', to='wip.Block'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
    ]
