# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0033_auto_20161031_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='count_segments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='count_words',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='segment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
