# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0034_auto_20161105_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name=b'plain text extracted')),
                ('html', models.TextField(blank=True, null=True, verbose_name=b'original text with tags')),
                ('is_fragment', models.BooleanField(default=False, verbose_name=b'is substring of a segment')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'creation date')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language', verbose_name=b'source language')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site', verbose_name=b'source site')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name=b'translation of plain text')),
                ('html', models.TextField(blank=True, null=True, verbose_name=b'translation of the original text with tags')),
                ('timestamp', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language', verbose_name=b'target language')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Segment', verbose_name=b'source segment')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.IntegerField(choices=[(0, 'site owner'), (1, 'site manager'), (2, 'linguist'), (3, 'revisor'), (4, 'translator'), (5, 'guest')], default=5, verbose_name=b'role type')),
                ('level', models.IntegerField(help_text='level of experience/reliability: let try to use the range 1 to 5 (top level)', verbose_name=b'level')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'role creation date')),
                ('creator', models.ForeignKey(help_text=b'who granted this role', on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name=b'role creator')),
                ('site', models.ForeignKey(help_text=b'leave undefined for a global role', null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site', verbose_name=b'site/project')),
                ('source_language', models.ForeignKey(help_text=b'leave undefined if role applies to any source language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='wip.Language', verbose_name=b'source language')),
                ('target_language', models.ForeignKey(help_text=b'can be undefined only for some role types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='wip.Language', verbose_name=b'target language')),
                ('user', models.ForeignKey(help_text=b'whom this role was granted', on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL, verbose_name=b'role owner')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.UserRole'),
        ),
    ]
