# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0036_auto_20161203_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.IntegerField(choices=[(1, 'Translation Memory'), (2, 'Machine Translation')], verbose_name=b'translation source type')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=b'comment'),
        ),
        migrations.AddField(
            model_name='segment',
            name='is_comment_settled',
            field=models.BooleanField(default=False, verbose_name=b'comment is settled'),
        ),
        migrations.AddField(
            model_name='translation',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name=b'locked'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translation_type',
            field=models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Translation Memory'), (2, 'Machine Translation'), (3, 'Manual')], default=0, verbose_name=b'translation type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.UserRole', verbose_name=b'user role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_type',
            field=models.IntegerField(choices=[(0, 'Site owner'), (1, 'Site manager'), (2, 'Linguist'), (3, 'Revisor'), (4, 'Translator'), (5, 'Guest')], default=5, verbose_name=b'role type'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translation_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.TranslationSource', verbose_name=b'translation source'),
        ),
    ]
