# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0037_auto_20161204_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='is_invariant',
            field=models.BooleanField(default=False, verbose_name=b'invariant'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='is_fragment',
            field=models.BooleanField(default=False, verbose_name=b'fragment'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_segment', to='wip.Segment', verbose_name=b'source segment'),
        ),
    ]
