# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0039_auto_20170516_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
