# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0040_auto_20170516_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='segment',
            name='in_use',
            field=models.BooleanField(default=True, verbose_name='in use'),
        ),
        migrations.AlterField(
            model_name='block',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_parents', through='wip.BlockEdge', to='wip.Block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language'),
        ),
        migrations.AlterField(
            model_name='block',
            name='webpages',
            field=models.ManyToManyField(blank=True, related_name='block', through='wip.BlockInPage', to='wip.Webpage', verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='block',
            name='xpath',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='response_code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proxy', to='wip.Language'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='robots_txt',
            field=models.TextField(blank=True, help_text='The virtual content of the robots.txt page.', null=True, verbose_name='robots.txt'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='translate_deny',
            field=models.TextField(blank=True, help_text='Paths of pages not to processed online by the proxy', null=True, verbose_name='Deny translation'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='original text with tags'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='is_comment_settled',
            field=models.BooleanField(default=False, verbose_name='comment is settled'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='is_fragment',
            field=models.BooleanField(default=False, verbose_name='fragment'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='is_invariant',
            field=models.BooleanField(default=False, verbose_name='invariant'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language', verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Site', verbose_name='source site'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='plain text extracted'),
        ),
        migrations.AlterField(
            model_name='site',
            name='checksum_deny',
            field=models.TextField(blank=True, help_text='Patterns identifying lines in body not affecting page checksum', null=True, verbose_name='Exclude from checksum'),
        ),
        migrations.AlterField(
            model_name='site',
            name='deny',
            field=models.TextField(blank=True, help_text='Paths the spider should not follow', null=True, verbose_name='Deny spyder'),
        ),
        migrations.AlterField(
            model_name='site',
            name='extract_deny',
            field=models.TextField(blank=True, help_text='Paths of pages the string extractor should skip', null=True, verbose_name='Deny extractor'),
        ),
        migrations.AlterField(
            model_name='site',
            name='invariant_words',
            field=models.TextField(blank=True, help_text='Custom invariant words', null=True, verbose_name='Custom invariant words'),
        ),
        migrations.AlterField(
            model_name='site',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_site', to='wip.Language'),
        ),
        migrations.AlterField(
            model_name='site',
            name='path_prefix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='srx_initials',
            field=models.TextField(blank=True, help_text='Initials to be made explicit as SRX rules', null=True, verbose_name='Custom initials'),
        ),
        migrations.AlterField(
            model_name='site',
            name='srx_rules',
            field=models.TextField(blank=True, help_text='Custom SRX rules extending the standard set', null=True, verbose_name='Custom SRX rules'),
        ),
        migrations.AlterField(
            model_name='site',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='site', through='wip.SiteTheme', to='django_diazo.Theme', verbose_name='diazo themes'),
        ),
        migrations.AlterField(
            model_name='site',
            name='translate_deny',
            field=models.TextField(blank=True, help_text='Paths of pages not to be submitted to offline translation', null=True, verbose_name='Deny translation'),
        ),
        migrations.AlterField(
            model_name='string',
            name='path',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='string',
            name='string_type',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'term'), (2, 'segment'), (3, 'fragment')], default=0, null=True, verbose_name='string type'),
        ),
        migrations.AlterField(
            model_name='translatedversion',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_version', to='wip.Webpage'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='alignment',
            field=models.TextField(blank=True, null=True, verbose_name='source to target alignment'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='alignment_type',
            field=models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Translation Memory'), (2, 'Machine Translation'), (3, 'Manual')], default=0, verbose_name='alignment type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='locked'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wip.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_translation', to='wip.Segment', verbose_name='source segment'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='target text'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.TranslationSource', verbose_name='translation source'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Translation Memory'), (2, 'Machine Translation'), (3, 'Manual')], default=0, verbose_name='translation type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.UserRole', verbose_name='user role'),
        ),
        migrations.AlterField(
            model_name='translationsource',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Translation Memory'), (2, 'Machine Translation')], verbose_name='translation source type'),
        ),
        migrations.AlterField(
            model_name='txu',
            name='entry_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id by provider'),
        ),
        migrations.AlterField(
            model_name='txu',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='txu source'),
        ),
        migrations.AlterField(
            model_name='txu',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='txu', through='wip.TxuSubject', to='wip.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='role creation date'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='who granted this role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name='role creator'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='level',
            field=models.IntegerField(help_text='level of experience/reliability: let try to use the range 1 to 5 (top level)', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_type',
            field=models.IntegerField(choices=[(0, 'Site owner'), (1, 'Site manager'), (2, 'Linguist'), (3, 'Revisor'), (4, 'Translator'), (5, 'Guest')], default=5, verbose_name='role type'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='site',
            field=models.ForeignKey(help_text='leave undefined for a global role', null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site', verbose_name='site/project'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='source_language',
            field=models.ForeignKey(help_text='leave undefined if role applies to any source language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='wip.Language', verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='target_language',
            field=models.ForeignKey(help_text='can be undefined only for some role types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='wip.Language', verbose_name='target language'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='whom this role was granted', on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL, verbose_name='role owner'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='page', through='wip.BlockInPage', to='wip.Block', verbose_name='blocks'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Possibly overrides the site language', null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Language'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='last_checked',
            field=models.DateTimeField(help_text='Last time the page fetched with success', null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='last_checked_response_code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='last_unfound',
            field=models.DateTimeField(help_text="Last time the page wasn't found", null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='no_translate',
            field=models.BooleanField(default=False, verbose_name='NoTr'),
        ),
    ]
