# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0041_auto_20171212_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ('role_type', 'level'), 'verbose_name': 'user role', 'verbose_name_plural': 'user roles'},
        ),
        migrations.AlterField(
            model_name='translation',
            name='alignment',
            field=models.TextField(blank=True, null=True, verbose_name='alignment'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_translation', to='wip.Segment', verbose_name='segment'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.UserRole', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_type',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Owner'), (2, 'Linguist'), (3, 'Revisor'), (4, 'Translator'), (5, 'Guest')], default=5, verbose_name='role type'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='site',
            field=models.ForeignKey(blank=True, help_text='leave undefined for a global role', null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Site', verbose_name='site/project'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='source_language',
            field=models.ForeignKey(blank=True, help_text='leave undefined if role applies to any source language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='wip.Language', verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='target_language',
            field=models.ForeignKey(blank=True, help_text='can be undefined only for some role types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='wip.Language', verbose_name='target language'),
        ),
    ]
