# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0042_auto_20171218_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='in_use',
            field=models.IntegerField(default=0, verbose_name='in use'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_type',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Owner'), (2, 'Manager'), (3, 'Linguist'), (4, 'Translator'), (5, 'Client')], default=5, verbose_name='role type'),
        ),
    ]
