# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0043_auto_20171228_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='multi_bips_xpaths',
            field=models.TextField(blank=True, help_text='xpaths allowing mutiple bips with same xpath', null=True, verbose_name='Multi-bips xpaths'),
        ),
    ]
