# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0044_webpage_multi_bips_xpaths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='multi_bips_xpaths',
        ),
        migrations.AddField(
            model_name='block',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='last seen'),
        ),
        migrations.AddField(
            model_name='site',
            name='variable_regions',
            field=models.TextField(blank=True, help_text='Path-xpath combinations identifying page regions with frequently changing content', null=True, verbose_name='Variable content regions'),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
    ]
