# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0045_auto_20180304_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_block_extraction',
            field=models.DateTimeField(help_text='Last time blocks were extracted from site pages', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_crawled',
            field=models.DateTimeField(help_text='Last time the site was crawled', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_fetched',
            field=models.DateTimeField(help_text='Last time new versions of site pages were fetched', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_segment_extraction',
            field=models.DateTimeField(help_text='Last time segments were extracted from site pages', null=True),
        ),
    ]
