# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0047_auto_20180313_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageversion',
            options={'verbose_name': 'page version', 'verbose_name_plural': 'page versions'},
        ),
        migrations.AddField(
            model_name='pageversion',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wip.Scan'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cache_type',
            field=models.IntegerField(choices=[(0, 'cache for translation'), (1, 'cache for publishing')], default=0, verbose_name='cache type'),
        ),
    ]
