# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0048_auto_20180320_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='block_count',
            field=models.IntegerField(default=0, verbose_name='block count'),
        ),
        migrations.AddField(
            model_name='site',
            name='http_server',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'Apache'), (2, 'Nginx')], default=0, null=True, verbose_name='http server type'),
        ),
    ]
