# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0049_auto_20180323_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name': 'site scan', 'verbose_name_plural': 'site scans'},
        ),
        migrations.AddField(
            model_name='proxy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='client_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_block_extraction',
            field=models.DateTimeField(blank=True, help_text='Last time blocks were extracted from site pages', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_crawled',
            field=models.DateTimeField(blank=True, help_text='Last time the site was crawled', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_fetched',
            field=models.DateTimeField(blank=True, help_text='Last time new versions of site pages were fetched', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_segment_extraction',
            field=models.DateTimeField(blank=True, help_text='Last time segments were extracted from site pages', null=True),
        ),
    ]
