# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0050_auto_20180330_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.IntegerField(choices=[(1, 'GoogleTranslate'), (2, 'DeepL'), (3, 'Microsoft Translator'), (5, 'MyMemory')], verbose_name='service type')),
                ('secret_1', models.CharField(blank=True, default='', max_length=100)),
                ('secret_2', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateTimeField(blank=True, help_text='start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='end date', null=True)),
                ('order', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscribed_by_site', to='wip.Site')),
            ],
            options={
                'ordering': ('order', 'service_type'),
                'verbose_name': 'service subscription',
                'verbose_name_plural': 'service subscription',
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='text_position',
            field=models.IntegerField(choices=[(0, 'element'), (1, 'attribute'), (2, 'meta tag'), (3, 'javascript'), (4, 'json')], default=0, verbose_name='text position'),
        ),
    ]
