# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0051_auto_20180403_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='translation_source',
        ),
        migrations.AddField(
            model_name='translation',
            name='service_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'GoogleTranslate'), (2, 'DeepL'), (3, 'Microsoft Translator'), (5, 'MyMemory')], default=0, verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='service_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'GoogleTranslate'), (2, 'DeepL'), (3, 'Microsoft Translator'), (5, 'MyMemory')], verbose_name='service type'),
        ),
        migrations.DeleteModel(
            name='TranslationSource',
        ),
    ]
