# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0052_auto_20180404_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='text_word_segmented',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='translation',
            name='text_word_segmented',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='service_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Google'), (2, 'DeepL'), (3, 'Microsoft'), (5, 'MyMemory')], verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='alignment_type',
            field=models.IntegerField(choices=[(0, '?'), (1, 'TM'), (2, 'MT'), (3, 'M')], default=0, verbose_name='alignment type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='service_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Google'), (2, 'DeepL'), (3, 'Microsoft'), (5, 'MyMemory')], default=0, verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.IntegerField(choices=[(0, '?'), (1, 'TM'), (2, 'MT'), (3, 'M')], default=0, verbose_name='translation type'),
        ),
    ]
