# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0053_auto_20180501_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTransformationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', help_text='optional path filter', max_length=200)),
                ('xpath', models.CharField(blank=True, default='', help_text='Xpath filter', max_length=200)),
                ('rule_type', models.IntegerField(choices=[(0, ''), (1, 'Drop')], default=1, verbose_name='rule type')),
                ('order', models.IntegerField(default=0, verbose_name='order of execution')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_used_for_proxy', to='wip.Proxy')),
            ],
            options={
                'verbose_name_plural': 'rules used for proxy',
                'verbose_name': 'rule used for proxy',
            },
        ),
    ]
