# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0054_proxytransformationrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxytransformationrule',
            options={'verbose_name': 'proxy transformation rule', 'verbose_name_plural': 'proxy transformation rules'},
        ),
        migrations.AddField(
            model_name='proxy',
            name='custom_text',
            field=models.TextField(blank=True, help_text='Custom fixed lines of text', null=True, verbose_name='Custom text'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='head_values',
            field=models.TextField(blank=True, help_text='Customization of head elements', null=True, verbose_name='Head values'),
        ),
    ]
